language: php

php:
  - 5.6
  - 7.0
  - 7.1

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

#matrix:
#  include:
#    - php: 5.5
#      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
#  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $TRAVIS_PHP_VERSION == '7.1' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
