speicher210_monsum_notification_subscription_created:
  path: /notification/subscription/created
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Subscription:created

speicher210_monsum_notification_subscription_changed:
  path: /notification/subscription/changed
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Subscription:changed

speicher210_monsum_notification_subscription_canceled:
  path: /notification/subscription/canceled
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Subscription:canceled

speicher210_monsum_notification_subscription_closed:
  path: /notification/subscription/closed
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Subscription:closed

speicher210_monsum_notification_subscription_reactivated:
  path: /notification/subscription/reactivated
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Subscription:reactivated

speicher210_monsum_notification_customer_created:
  path: /notification/customer/created
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Customer:created

speicher210_monsum_notification_customer_changed:
  path: /notification/customer/changed
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Customer:changed

speicher210_monsum_notification_customer_deleted:
  path: /notification/customer/deleted
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Customer:deleted

speicher210_monsum_notification_payment_created:
  path: /notification/payment/created
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Payment:created

speicher210_monsum_notification_payment_chargeback:
  path: /notification/payment/chargeback
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Payment:chargeback

speicher210_monsum_notification_payment_failed:
  path: /notification/payment/failed
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Payment:failed

speicher210_monsum_notification_payment_refunded:
  path: /notification/payment/refunded
  methods: [POST]
  defaults:
    _controller: Speicher210MonsumBundle:Notification/Payment:refunded